# This file was generated by GoReleaser. DO NOT EDIT.
cask "aindez" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "c4d30bfc67ce262ad3e71292a119e99232f40245ef797694467cba731d292953"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d86b36dde8bb8d70dc3b423d4e8a7e1eec78aa0d01be13c3640557b8d7cf09e1"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "80b1e26cd4df0c748671ef3b2d76185f467bd40c92451043d2be33385c93b9dd"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "13d7c6454719a6fb79b3b05a6dffe7c78b5392ecedd6a47c30c7e64940fb3362"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aindez"
  desc "CLI de la plataforma Aindez (CRM, ATS y ERP desde la terminal)"
  homepage "https://github.com/aindez-tech/aindez-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aindez"

  # No zap stanza required
end
