# This file was generated by GoReleaser. DO NOT EDIT.
cask "aindez" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "7c20b93ef5ce383b4ae13d62de9ad6cca0e1ee4a6b030d3971cf0c55ecef27d4"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "59a3356f507fc32bc62f1d9ad1501e6294d1f1cb8c9eeae394a534235525bfc0"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6da54c8cde616590adf5e0932a0bc420db5cf7651aaf2af8594fa6313a65e6b5"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5675b9022a1f15f4373a2eb9448d0677cbb49417e66e97353ff76fd72858103"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aindez"
  desc "CLI de la plataforma Aindez (CRM, ATS y ERP desde la terminal)"
  homepage "https://github.com/aindez-tech/aindez-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aindez"

  # No zap stanza required
end
