# This file was generated by GoReleaser. DO NOT EDIT.
cask "aindez" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "9c4968261463b1d70d24439852ab0e5d941a1aa3c15833cce6a4ef164cd5c1fe"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d79fb36960a40a4f80a6a8b44f02366b154a1d860d5b5d3a87da461d3201af45"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9b2c22382d503869cde3a59cc51e06493dc2099699496808067c011cd50b903c"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "632ec35f2c57a227db1a38dac1f83e9aff69877cb768eff8cf7014a8bcb7d64c"
      url "https://github.com/aindez-tech/aindez-releases/releases/download/v#{version}/aindez_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aindez"
  desc "CLI de la plataforma Aindez (CRM, ATS y ERP desde la terminal)"
  homepage "https://github.com/aindez-tech/aindez-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aindez"

  # No zap stanza required
end
